distributable:
  url: https://registry.npmjs.org/@mongosh/cli-repl/-/cli-repl-{{version}}.tgz
  strip-components: 1
display-name: mongosh
versions:
  npm: '@mongosh/cli-repl'
dependencies:
  nodejs.org: '*'
build:
  dependencies:
    npmjs.com: '*'
  script:
    - npm install $ARGS .
    - run: ln -s ../libexec/bin/mongosh mongosh
      working-directory: "{{prefix}}/bin"
  env:
    ARGS:
      - -ddd
      - --global
      - --build-from-source
      - --prefix={{prefix}}/libexec
      - --unsafe-perm
provides:
  - bin/mongosh
test:
  script:
    - mongosh --version | grep {{version}}
    - mongosh --nodb --eval "print('#ok#')" | grep '#ok#'
    - mongosh --smokeTests
