distributable:
  url: https://registry.npmjs.org/zx/-/zx-{{version}}.tgz
  strip-components: 1
display-name: zx
versions:
  npm: zx
dependencies:
  nodejs.org: '*'
build:
  dependencies:
    npmjs.com: '*'
  script:
    - npm install $ARGS .
    - run: ln -s ../libexec/bin/zx zx
      working-directory: "{{prefix}}/bin"
  env:
    ARGS:
      - -ddd
      - --global
      - --build-from-source
      - --prefix={{prefix}}/libexec
      - --unsafe-perm
provides:
  - bin/zx
test:
  script:
    - zx --version | grep {{version}}
    - zx test.mjs | grep "name is bar"
    - ls | grep bar
